#!/bin/sh
# This script attempts to install PyTorch in a virtual environment (local
# directory = ./pytorch).  It will try the conda installer by default, but if
# that fails, then try the pip installer instead:
# >rm -rf pytorch
# >env installer=pip setup
# It then attempts to install PyFlow.  Note that successful compilation
# requires C++ and Python development libraries:
# >sudo dnf install -y gcc-c++ python3-devel
# Root is not required otherwise, and all changes are local, so uninstalling
# the project is a simple matter of removing its directory.

cd $(dirname ${0})

if [[ ! -e "weights/FBPNSR_RBPN_V4_REF_Lr_STAR_ST.pth" ]]
then
  echo "Downloading pretrained weights..."
  echo

  wget -P weights http://technology.research-lab.ca/wp-content/uploads/FBPNSR_RBPN_V4_REF_Lr_STAR_ST.pth
  echo
fi

if [[ -e "pytorch/bin/activate" ]]
then
  source pytorch/bin/activate
else
  echo "Setting up a virtual environment for PyTorch..."
  echo

  if [[ "$installer" == "pip" ]]
  then
    # Install via pip:
    python3 -m venv pytorch
    source pytorch/bin/activate
    pip --no-cache-dir install --upgrade pip
  else
    # Install via conda:
    if ! ls pytorch/*.sh >/dev/null 2>&1
    then
      mkdir -p pytorch
      # Note: If this is the wrong link, then please download Miniconda
      # manually and try again...
      wget -P pytorch https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    fi

    sh pytorch/*.sh -b -p pytorch -f
    rm pytorch/*.sh
    source pytorch/bin/activate
    # Older Python is required to reduce forward-compatibility problems:
    conda install -y python=3.7
  fi
  echo
fi

if [[ "$CONDA_DEFAULT_ENV" ]]
then
  installer=conda
else
  installer=pip
fi
echo "Installing PyTorch - using $installer installer..."
echo

if [[ "$installer" == "pip" ]]
then
  # Install via pip:
  cat <<EOF >pytorch/requirements.txt
scikit-image
opencv-python
torchvision==0.8.2
Cython
scipy==1.2.0
EOF

  pip --no-cache-dir install -r pytorch/requirements.txt
else
  # Install via conda:
  cat <<EOF >pytorch/requirements.txt
scikit-image
opencv
torchvision=0.8.2
cython
scipy=1.2.0
EOF

  conda install -y --file pytorch/requirements.txt
  # Conda installs FFmpeg with x264 disabled :-(
  mv pytorch/bin/ffmpeg pytorch/bin/ffmpeg.conda
fi
# Check results using:
# >python -c 'from torch.utils.collect_env import main; main()'
echo

if ! ls pyflow.cpython-*.so >/dev/null 2>&1
then
  echo "Installing PyFlow..."
  echo

  cd pyflow
  python setup.py build_ext -i
  cd ..
  if ! ls pyflow/pyflow.cpython-*.so >/dev/null 2>&1
  then
    echo
    echo "Pyflow installation failed."
    exit
  fi
  ln -s pyflow/pyflow.cpython-*.so .
  echo
fi

# Attempt to run the script:
echo
upscale --help
echo

# ffmpeg is optional; used for extracting frames from video files.
if ! which ffmpeg >/dev/null 2>&1
then
  echo "Just noting that ffmpeg is not found."
  echo
fi

echo "If there are no errors, then setup completed successfully.  Now run:"
echo ">source $(dirname ${0})/pytorch/bin/activate"
echo ">$(dirname ${0})/upscale --help"
